# Generated by Django 6.0.2 on 2026-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
