# Generated by Django 6.0.2 on 2026-03-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B2C', 'Bireysel'), ('B2B', 'Kurumsal')], default='B2C', max_length=3)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tax_number', models.CharField(blank=True, max_length=20)),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('TRENDYOL', 'Trendyol'), ('AMAZON', 'Amazon'), ('HEPSIBURADA', 'Hepsiburada'), ('N11', 'N11'), ('WEBSITE', 'Web Sitesi'), ('STORE', 'Fiziksel Mağaza'), ('OTHER', 'Diğer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('shop_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_channels',
            },
        ),
    ]
